version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: prodemge-db
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.81

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 172.18.0.82

# docker network create --subnet=172.18.0.0/16 php-apache

networks:
  default:
    external:
      name: php-apache

volumes:
  mysql-data:
